export const sampleProducts = [
  {
    name: "Tênis Nike Revolution 5 Max",
    slug: "nike-slim-shirt",
    image: "https://imgcentauro-a.akamaihd.net/230x230/94313731.jpg",
    category: "shoe",
    brand: "Nike",
    price: 249.99,
    countInStock: 10,
    description: "high quality shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "Tênis Nike Revolution 5",
    slug: "nike revolution 5",
    image: "https://imgcentauro-a.akamaihd.net/230x230/94313762.jpg",
    category: "shoe",
    brand: "Nike",
    price: 249.99,
    countInStock: 10,
    description: "high quality shirt",
    rating: 4.7,
    numReviews: 10,
  },
  {
    name: "Tênis Asics Patriot 12 Noosa",
    slug: "asics patriot",
    image: "https://imgcentauro-a.akamaihd.net/230x230/95077714.jpg",
    category: "shoe",
    brand: "Asics",
    price: 249.99,
    countInStock: 10,
    description: "high quality shirt",
    rating: 4.7,
    numReviews: 10,
  },
  {
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    image: "",
    category: "Shirts",
    brand: "Nike",
    price: 1200,
    countInStock: 10,
    description: "high quality shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "Adidas Fit Shirt",
    slug: "adidas-slim-shirt",
    image: "",
    category: "Shirts",
    brand: "Adidas",
    price: 1500,
    countInStock: 0,
    description: "high quality shirt",
    rating: 4.3,
    numReviews: 13,
  },
  {
    name: "Puma Fit Pant",
    slug: "puma-slim-pant",
    image: "",
    category: "Pants",
    brand: "Puma",
    price: 2100,
    countInStock: 20,
    description: "high quality Pants",
    rating: 3.8,
    numReviews: 22,
  },
  {
    name: "Nike Slim Pant",
    slug: "nike-slim-Pant",
    image: "",
    category: "Pants",
    brand: "Nike",
    price: 3400,
    countInStock: 15,
    description: "high quality pants",
    rating: 4.3,
    numReviews: 14,
  },
];
