import { Product } from "../interface/product";

const sampleProducts: Product[] = [
  {
    title: "Tênis Nike Revolution 5 Max",
    slug: "nike-slim-shirt",
    image: "https://imgcentauro-a.akamaihd.net/230x230/94313731.jpg",
    category: "Sneakers",
    color: "black",
    brand: "Nike",
    prevPrice: 249.99,
    newPrice: 200,
    countInStock: 10,
    description: "high quality shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    title: "Tênis Nike Revolution 5",
    slug: "nike revolution 5",
    image: "https://imgcentauro-a.akamaihd.net/230x230/94313762.jpg",
    category: "Sneakers",
    color: "blue",
    brand: "Nike",
    prevPrice: 249.99,
    newPrice: 200,
    countInStock: 10,
    description: "high quality shirt",
    rating: 4.7,
    numReviews: 10,
  },
  {
    title: "Nike Air Vapormax Plus",
    slug: "Air Vapormax Plus",
    image: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    category: "Sneakers",
    color: "red",
    brand: "Nike",
    prevPrice: 300.0,
    newPrice: 250,
    countInStock: 10,
    description: "high quality",
    rating: 4.5,
    numReviews: 7,
  },
  {
    title: "Tênis Asics Patriot 12 Noosa",
    slug: "asics patriot",
    image: "https://imgcentauro-a.akamaihd.net/230x230/95077714.jpg",
    category: "Sneakers",
    color: "light blue",
    brand: "Asics",
    prevPrice: 249.99,
    newPrice: 200,
    countInStock: 10,
    description: "high quality shirt",
    rating: 4.7,
    numReviews: 10,
  },

  {
    title: "Adidas Fit Shirt",
    slug: "adidas-slim-shirt",
    image: "../src/assets/image/camisa-black-adid.jpg",
    category: "Shirts",
    color: "black",
    brand: "Adidas",
    prevPrice: 180.0,
    newPrice: 100,
    countInStock: 0,
    description: "high quality shirt",
    rating: 4.3,
    numReviews: 13,
  },
  {
    title: "Puma Fit Pant",
    slug: "puma-slim-pant",
    image: "../src/assets/image/pants-puma.jpg",
    category: "Pants",
    color: "gray",
    brand: "Puma",
    prevPrice: 120.0,
    newPrice: 50,
    countInStock: 20,
    description: "high quality Pants",
    rating: 3.8,
    numReviews: 22,
  },
  {
    title: "Nike Slim Pant",
    slug: "nike-slim-Pant",
    image: "../src/assets/image/pants-black-nik.jpg",
    category: "Pants",
    color: "black",
    brand: "Nike",
    prevPrice: 149.99,
    newPrice: 100,
    countInStock: 15,
    description: "high quality pants",
    rating: 4.3,
    numReviews: 14,
  },
  {
    title: "Vans Unisex Low-Top",
    slug: "vans unisex",
    image: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    category: "Sandals",
    color: "blue",
    brand: "Vans",
    prevPrice: 109.99,
    newPrice: 50,
    countInStock: 2,
    description:
      "The iconic low-top sneaker that brought the Vans Original Sidestripe to life",
    rating: 4.0,
    numReviews: 14,
  },
  {
    title: "Bridal Sandals Glitter",
    slug: "bridal sandals",
    image: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    category: "heels",
    color: "black",
    brand: "Adidas",
    prevPrice: 119.99,
    newPrice: 50,
    countInStock: 5,
    description: "high sandals",
    rating: 4.5,
    numReviews: 10,
  },
  {
    title: "Amore Fashion Stilettos",
    slug: "amore fashion stilettos",
    image: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    category: "heels",
    color: "white",
    brand: "Adidas",
    prevPrice: 149.99,
    newPrice: 99.99,
    countInStock: 2,
    description: "high sandals",
    rating: 4.7,
    numReviews: 8,
  },
];

export default sampleProducts;
