export const sampleProducts = [
    {
      name: "Tênis Nike Revolution 5 Max",
      slug: "nike-slim-shirt",
      image: "https://imgcentauro-a.akamaihd.net/230x230/94313731.jpg",
      category: "Shoe",
      brand: "Nike",
      price: 249.99,
      countInStock: 10,
      description: "high quality shirt",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Tênis Nike Revolution 5",
      slug: "nike revolution 5",
      image: "https://imgcentauro-a.akamaihd.net/230x230/94313762.jpg",
      category: "Shoe",
      brand: "Nike",
      price: 249.99,
      countInStock: 10,
      description: "high quality shirt",
      rating: 4.7,
      numReviews: 10,
    },
    {
      name: "Tênis Asics Patriot 12 Noosa",
      slug: "asics patriot",
      image: "https://imgcentauro-a.akamaihd.net/230x230/95077714.jpg",
      category: "Shoe",
      brand: "Asics",
      price: 249.99,
      countInStock: 10,
      description: "high quality shirt",
      rating: 4.7,
      numReviews: 10,
    },
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      image: "../assets/image/camisa-white-nike.jpg",
      category: "Shirts",
      brand: "Nike",
      price: 1200,
      countInStock: 10,
      description: "high quality shirt",
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Adidas Fit Shirt",
      slug: "adidas-slim-shirt",
      image: "../assets/image/camisa-black-adid.jpg",
      category: "Shirts",
      brand: "Adidas",
      price: 1500,
      countInStock: 0,
      description: "high quality shirt",
      rating: 4.3,
      numReviews: 13,
    },
    {
      name: "Puma Fit Pant",
      slug: "puma-slim-pant",
      image: "../assets/image/pants-puma.jpg",
      category: "Pants",
      brand: "Puma",
      price: 2100,
      countInStock: 20,
      description: "high quality Pants",
      rating: 3.8,
      numReviews: 22,
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-Pant",
      image: "../assets/image/pants-black-nik.jpg",
      category: "Pants",
      brand: "Nike",
      price: 3400,
      countInStock: 15,
      description: "high quality pants",
      rating: 4.3,
      numReviews: 14,
    },
    {
      name: "Nike Slim Pant Gray",
      slug: "nike-slim-Pant",
      image: "../assets/image/pants-gray-nik.jpg",
      category: "Pants",
      brand: "Nike",
      price: 3400,
      countInStock: 15,
      description: "high quality pants",
      rating: 4.3,
      numReviews: 14,
    },
  ];
  